name: Build Cheat Engine

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - uses: gcarreno/setup-lazarus@v3
      with:
        lazarus-version: 2.2.2

    - run: lazbuild --build-mode="Release" "Cheat Engine/cheatengine.lpi"

    - name: Copy TCC and Dependencies
      shell: pwsh
      run: |
        $srcTcc = "Cheat Engine/tcc"
        $destTcc = "Cheat Engine/bin/tcc"
        if (Test-Path $srcTcc) {
            if (!(Test-Path $destTcc)) {
                New-Item -ItemType Directory -Force -Path $destTcc | Out-Null
            }
            Copy-Item -Recurse -Force "$srcTcc/*" $destTcc
        }

    - name: Upload Full Bin Folder
      uses: actions/upload-artifact@v4
      with:
        name: CheatEngine-Full
        path: Cheat Engine/bin/
